# [repositories.cnb]
# url = "https://pypi.cnb.cool/topia.ogz/tpip/-/packages/simple"


# [global]
# index-url = "https://cnb:aXrEPNfIvdl1429HcgujcahrADC@https:pypi.cnb.cool/topia.ogz/tpip/-/packages/simple"